### ISSUE TITLE
[Guild-System] Tasks:

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#169]
Tasks

Menüseiten: (siehe Guild UI Konzept)
- Mitgliederverwaltung
- Gilden Einstellungen
- Gildenmenü-Hauptseite
- Gildenextras 

Generell:
- Einführung korrekter Gildenränge mit Rechte
- Complete Guild Bank System (draw and with draw)
- withdraw nur entsprechend der Gildenberechtigung für Leader, Offis und Adel

Gildengründung:
Gründung am Spawn

**Comment by TimK1998** [comment]
Ich denke hier ist alles jetzt eingebaut. Extras fehlen halt noch.

**Comment by Timkoe** [comment]
Lass uns das noch testen.
