### ISSUE TITLE
[G Fight] Click cooldown auf Gildenblock einbauen

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#192]

**Comment by Timkoe** [comment]
Funktioniert aktuell noch nicht richtig falls eingebaut

**Comment by Kyraja** [comment]
Der Klick-Cooldown liegt bei ~1 Sekunde. Wie hoch soll er sein?

**Comment by Timkoe** [comment]
Der Cooldown funktioniert insgesamt gerade nicht
