### ISSUE TITLE
Spieler können sich nach oben boosten auf geschützten gebieten durch block placing

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#200]

**Comment by Kyraja** [comment]
Wie hätten sie es denn gerne? Wenn es jemand versucht kicken? ich meine das ist leider minecraft... wenn ich das placen cancel, dann geht dat nunmal hoch

**Comment by Timkoe** [comment]
Denke wir können / müssen das wohl als will not fix schliessen.
