### ISSUE TITLE
[Guild-System] Task: G steal entfernen / Gold direkt schicken

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#212]
Neues Design zum Gildenlooting:
Statt G steal sollen direkt nach erfolgreichem Gildenangriff 25% Des Goldes der Verlierer auf dem Gildenkonto der Angreifer landen.

**Comment by TimK1998** [comment]
NUr 20%??? Ist ja mega lame

**Comment by Timkoe** [comment]
komm discord
