### ISSUE TITLE
[Chat System]Zeitschuss Teil von Beschreibung fehlt

### ISSUE THREAD

**Issue by Ricokoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#219]
Im /slots Menü vom Waldläufer fehlt bei der Skillbeschreibung des Zeitschuss der letzte Teil, er wird nach "(...), fügt ihm Schaden zu " abgehackt

**Comment by Timkoe** [comment]
Ka wieso das abgehackt wird, vllt zu lang?
