### ISSUE TITLE
[Chat System] Schattenklinge /slots Schreibfehler/Ordnungsfehler

### ISSUE THREAD

**Issue by Ricokoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#222]
1. Enterhaken kommt in der Reihenfolge vor Schattenschleier, obwohl Schattenschleier 10 Level früher freigeschaltet wird als Enterhaken
2.Dolchstoss hat den Namen skill_dolchstoss_name und in der Beschreibung steht nur skill_dolchstoss_description und es hat die selben Mana und Cooldown Werte wie Schattenstoss und ebenfalls das selbe Freischaltlevel
3. Die Beschreibung von Schattenstoss ist unvollständig, endet abrupt

**Comment by Timkoe** [comment]
Torre: Dolchstoss ist der alte Name von Schattenstoss, deswegen selbe Werte etc., sollte vollständig removed/ nicht mehr angezeigt werden

**Comment by Timkoe** [comment]
Bitte entsprechend entfernen.
