### ISSUE TITLE
[Belagerungsskill]Obsidianbrecher/Sprengladung funktioniert nicht so wie es sollte

### ISSUE THREAD

**Issue by stefanomazz** [LostKingdoms/Lost-Kingdoms-IssueTracker#234]
Im Bild hab ich 1x Sprengladung und 1x Obsidianbrecher benutzt.

https://i.badlion.net/oG9eiosaLxym9bA2H7e3PZ.png

Die Blöcke hinter den Blöcken sollten eigentlich nicht zerstört werden.

**Comment by Timkoe** [comment]
@stefanomazz bitte checken ob es jetzt passt.

**Comment by stefanomazz** [comment]
Funktioniert!
