### ISSUE TITLE
[Guild-System]Gildenfight wird nach töten nicht gestartet

### ISSUE THREAD

**Issue by AioAioAio** [LostKingdoms/Lost-Kingdoms-IssueTracker#236]
Gildenfight wird nach töten nicht gestartet wie im Wiki beschrieben

Passiver Start:

Ein Gildenkampf wird ausgelöst, wenn eine feindliche Gilde ein Mitglied der angegriffenen Gilde auf Core Gildengebiet tötet oder mindestens 3 Mitglieder in der Grenzzone innerhalb von 30 Minuten tötet.

**Comment by TimK1998** [comment]
Ist noch nicht eigebaut
