### ISSUE TITLE
[Class-System]Changelog Pre Test

### ISSUE THREAD

**Issue by Torre1234** [LostKingdoms/Lost-Kingdoms-IssueTracker#240]
Hier wie besprochen die Liste an Skill Änderungen vor dem Test einmal übersichtlich:

Barbar: 
Zyklonaxt: Cooldown: **15s**
Spalten: **Remove Blind**

Schattenklinge:
Trittnägel: Cooldown: **15s**
Dunkle Wiederkehr: CD **50s**

Hexer:
Eisfesseln: CD **15s**
Blitzschlag: CD **40s**
Zeitkrümmung: CD: **100s** NEW:**100** initial cast **Dmg**,

Templer:
Siegel des Zorns: CD **15s**
Helfende Hand: CD **45s**
Widerstand: CD **40s**

Waldläufer:
Stachelpfeil:NEW:Add **Blindness I 3s**
Waldrausch: Change to **Speed III** for **15s**

(maybe)to do Post Test:
-Lebenswerte je nach time to kill anpassen
-Waldläufer Ultimate reworken
-Trittnägel Sound&Animation
-Himmlische Leichtigkeit FallDmg Interaktion hinzufügen
-Giftpfeil und Giftklingen Buff
-Axtwurf Nerf
-Feuerresistenz-Dauer von Klassen Skills reduzieren, dafür jeweils CD auch runter

**Comment by Timkoe** [comment]
Ich schaue alles durch.

**Comment by TimK1998** [comment]
Beschreibungen bitte wenn nötig auch ändern, z.B. bei Stachelpfeil.

**Comment by Timkoe** [comment]
Approved und wird geändert.

**Comment by Timkoe** [comment]
Done.
