### ISSUE TITLE
/admin reset setzt K/D etc nicht zurück

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#253]

**Comment by TimK1998** [comment]
@Timkoe  Das macht doch gar keinen Sinn. Der Reset soll doch eine Betrafungsmaßnahme sein. Da sollte doch nicht auch die komplette Statistik zurückgesetzt werden.

**Comment by Timkoe** [comment]
Wird jetzt durch Premium anders eingebaut, kann geschlossen werden.
