### ISSUE TITLE
Task: Punch Bogen enchant entfernen

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#255]
Punch Bogen enchant entfernen
ist komplett broken

**Comment by Timkoe** [comment]
Skill ist in Kombi mit Zeitschuss mehr oder weniger oneshot

**Comment by TimK1998** [comment]
Ja weil du einen absoluten Schadensboost wolltest und keinen relativen

**Comment by Timkoe** [comment]
der Damage ist nicht das Problem, sondern der Knockback
