### ISSUE TITLE
DB Manche Spieler erscheinen in Gilde manche nicht

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#264]

**Comment by Kyraja** [comment]
@TimK1998 Ich glaube es liegt daran, dass das UserJoin nicht richtig getriggert wird und dadurch die User nicht zur "onlineuserList" hinzugefügt bzw. removed werden. Außerdem müssten wir mal schauen mit den NamenTags stimmt bei rejoin auch noch etwas nicht

**Comment by TimK1998** [comment]
Jep, hängt alles mit #268 zusammen, da die Objekte unterschiedlich sind.
