### ISSUE TITLE
isFriendly für Gilden geht nicht

### ISSUE THREAD

**Issue by Kyraja** [LostKingdoms/Lost-Kingdoms-IssueTracker#268]
Ich glaube es ist noch ein Bug in der friendly Methode im User bei der Abfrage der Gilde. Ich stelle es bis Freitag noch auf uuid um weil object anscheidn nicht equal sind ^^

**Comment by TimK1998** [comment]
@Kyraja Habs schon auf UUid umgestellt und dann funktioniert das isFriendly auch wieder. Allerdings funktioniert alles andere nicht wenn die Objekte verschieden sind. Derjenige mit dem anderen Gildenobjekt bspw. sieht sich bei /g info nicht in der Gilde etc... Also muss man definitiv das Problem mit dem Objekt auch noch lösen.
