### ISSUE TITLE
Exp sharing berechnung falsch (muss mehr gechekt werden)

### ISSUE THREAD

**Issue by Timkoe** [LostKingdoms/Lost-Kingdoms-IssueTracker#286]

**Comment by TimK1998** [comment]
denke ich nicht

**Comment by Kyraja** [comment]
Wurde mit 3 Leuten getestet. Berechnung hatte immer funktioniert. Berechnung kann geprüft werden. Wenn wircklich ein bekannter Fehler auftritt, dann wieder öffnen.
